### ISSUE TITLE
Enhancement -> Style Setting for a custom background image

### ISSUE THREAD

**Issue by WinnerWind** [isaacfreeman/kakano-obsidian-theme#10]
I did not know that it was possible to have a custom background image as part of a theme in Obsidian, but now that I myself have gotten into making themes, I know that it is indeed possible.
After some digging, I found some sample code that can make this possible
```
.horizontal-main-container { /* below is the background image. Change it to whatever you want */
    background: url(https://images.unsplash.com/photo-1454496522488-7a8e488e8606?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2076&q=80);
    background-size: cover;
}
```
[Pulled from here](https://forum.obsidian.md/t/how-to-add-a-custom-image-as-a-background/53416)

The benefit of such a feature is immense. It can make different vaults stand out even more when Alt+Tabbing, or give the document a more "notebook" feel. Moreover, it can help vaults that use the same accent colour stick out from each other by simply changing the background image.

**Comment by isaacfreeman** [comment]
I've explored this a bit, and I think having a background image would work well for some themes, but isn't a good fit for Kakano. The problem is that the Kakano design puts text directly on the background. If there's also a background image it can make the text hard to read.

<img width="249" alt="Screenshot 2024-10-20 at 16 27 08" src="https://github.com/user-attachments/assets/7215d9b6-c08b-4268-a9bc-32cd2db45259">

If you're OK with that, or if you're happy to select an image that works well for your vault, here's a snippet you can use with Kakano.

```css
.app-container {
  --backgroundImageUrl: url(https://images.unsplash.com/photo-1454496522488-7a8e488e8606);
  --gradientOverlayPercentage: 50%;
  background-image: linear-gradient(
      to bottom,
      color-mix(
        in srgb,
        var(--theme-color-gradientTop) var(--gradientOverlayPercentage),
        transparent
      ),
      color-mix(
        in srgb,
        var(--theme-color-gradientBottom) var(--gradientOverlayPercentage),
        transparent
      )
    ),
    var(--backgroundImageUrl);
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
.workspace-split.mod-root {
  background: transparent;
}
```
There are two variables at the top to modify:
- `backgroundImageUrl` is web address for your image. I've used your example `https://images.unsplash.com/photo-1454496522488-7a8e488e8606`, but change it to whatever you like.
- `gradientOverlayPercentage` sets how much of the normal Kakano gradient background should be overlaid onto the image. My screenshot above has 50%, and I think you'll want it around 80% for a typical photographic image to keep text visible. If you have a very low-contrast image though, you could bring it down to zero.

Hope that's useful!
